spring:
      profiles.active: liyimaster
      aop.auto: false
      jpa.database : MYSQL
      suffix: .jsp
      datasource:
            type: com.alibaba.druid.pool.DruidDataSource
            name: liyiDataSourceName
            url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&useSSL=true
            username: root
            password: 1768872930
            driverClassName: com.mysql.jdbc.Driver
            initialSize: 1
            minIdle: 3
            maxActive: 20
            maxWait: 60000  # 配置获取连接等待超时的时间 
            timeBetweenEvictionRunsMillis: 60000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 
            minEvictableIdleTimeMillis: 30000 # 配置一个连接在池中最小生存的时间，单位是毫秒
            validationQuery: select 1 from dual
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false 
            poolPreparedStatements: true  # 打开PSCache，并且指定每个连接上PSCache的大小
            maxPoolPreparedStatementPerConnectionSize: 20 
            filters: stat,wall,slf4j # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
            connectionProperties: druidstat.mergeSql=true;druid.stat.slowSqlMillis=5000  # 通过connectProperties属性来打开mergeSql功能；慢SQL记录 
            useGlobalDataSourceStat: true # 合并多个DruidDataSource的监控数据
server:
      port: 8099
      context-path: /
logging:
      level:
            com.liyimaster: DEBUG
crossDomainFilter:
      origin: "*"